{% set version = "2.40.5" %}

package:
  name: spicetify-cli
  version: {{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v{{ version }}.tar.gz
  sha256: 0dc22f81a8d66c2c13fa4bd3af7434c3970b55643d27d1325e4f5eeb3b1da1b0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - spicetify-cli --help

about:
  home: https://github.com/spicetify-cli/spicetify-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  dev_url: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
