{% set version = "2.42.3" %}

package:
  name: spicetify-cli
  version: {{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v{{ version }}.tar.gz
  sha256: 2d1108bff0b3b6232e34b417fc7ff00fa661a04afd23f4ed877f2514696ab197

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - spicetify-cli --help

about:
  home: https://github.com/spicetify-cli/spicetify-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  dev_url: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
