{% set version = "2.38.5" %}

package:
  name: spicetify-cli
  version: {{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v{{ version }}.tar.gz
  sha256: bb72f491552d0f8fbe0ab3195c70884e8c4eb9c588f17ec77dcb4494aec70e52

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - spicetify-cli --help

about:
  home: https://github.com/spicetify-cli/spicetify-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  dev_url: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
