{% set version = "2.40.6" %}

package:
  name: spicetify-cli
  version: {{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v{{ version }}.tar.gz
  sha256: ca4e0c24f7077d9a43727ad63040d317ae9be39b167cdad010ed347ac28b2fd6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - spicetify-cli --help

about:
  home: https://github.com/spicetify-cli/spicetify-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  dev_url: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
