{% set version = "2.39.2" %}

package:
  name: spicetify-cli
  version: {{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v{{ version }}.tar.gz
  sha256: 33a1681a667de9492a87085227cfd73aabe8aba9cf217728a74df8adc0a062bc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - spicetify-cli --help

about:
  home: https://github.com/spicetify-cli/spicetify-cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  dev_url: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
