schema_version: 1

context:
  version: "2.42.10"

package:
  name: spicetify-cli
  version: ${{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v${{ version }}.tar.gz
  sha256: b001354eabbaa165433a6ced8c0e0c590a40464a5b7a6fbaf7328a83bd7c0cc3

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spicetify-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  homepage: https://github.com/spicetify-cli/spicetify-cli
  repository: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
