schema_version: 1

context:
  version: "2.42.13"

package:
  name: spicetify-cli
  version: ${{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v${{ version }}.tar.gz
  sha256: 4e6deed25d42f2f5b42cf70f33a08576c4e052f2a10f068a9def7a36513283ed

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spicetify-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  homepage: https://github.com/spicetify-cli/spicetify-cli
  repository: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
