schema_version: 1

context:
  version: "2.45.0"

package:
  name: spicetify-cli
  version: ${{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v${{ version }}.tar.gz
  sha256: 2e17c15a92093c62d011acd863f36148f8d5880292cadf41949eda320fd033c3

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spicetify-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  homepage: https://github.com/spicetify-cli/spicetify-cli
  repository: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
