schema_version: 1

context:
  version: "2.42.11"

package:
  name: spicetify-cli
  version: ${{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v${{ version }}.tar.gz
  sha256: f1b8fc1ed32a128d9d432971085c6d698eaf31f70d8294c349607eba74a3108f

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spicetify-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  homepage: https://github.com/spicetify-cli/spicetify-cli
  repository: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
