schema_version: 1

context:
  version: "2.43.1"

package:
  name: spicetify-cli
  version: ${{ version }}

source:
  url: https://github.com/spicetify/spicetify-cli/archive/v${{ version }}.tar.gz
  sha256: f7f577c90e9b6e502ab05891f83f657038beded57bd6d09ab4421f87bc2542dd

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - spicetify-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line tool to customize Spotify client
  homepage: https://github.com/spicetify-cli/spicetify-cli
  repository: https://github.com/spicetify-cli/spicetify-cli

extra:
  recipe-maintainers:
    - danielnachun
